In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
plt.rcParams ['figure.figsize']=(6,4)
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [6]:
df=pd.read_csv('owid-covid-data.csv')
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511

In [7]:
df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
count,7.949000e+04,79488.000000,78487.000000,6.997800e+04,70136.000000,78487.000000,79059.000000,79057.000000,78061.000000,69560.000000,...,73644.000000,50214.000000,74275.000000,75270.000000,58259.000000,57399.000000,37297.000000,67846.000000,77072.000000,74181.000000
mean,7.573865e+05,5479.157105,5470.167763,2.159074e+04,135.173107,119.453302,9162.663015,71.930109,71.861845,208.333068,...,19134.381586,13.318712,257.554426,7.807765,10.527537,32.655282,50.945810,3.031289,73.155779,0.727397
std,5.263169e+06,33750.043397,33250.601996,1.272449e+05,737.064162,673.901399,17757.007624,174.355151,147.587061,367.093644,...,19789.918144,19.931526,118.677814,3.961493,10.402358,13.474767,31.764836,2.464702,7.550402,0.150072
min,1.000000e+00,-74347.000000,-6223.000000,1.000000e+00,-1918.000000,-232.143000,0.001000,-2153.437000,-276.825000,0.001000,...,661.240000,0.100000,79.370000,0.990000,0.100000,7.700000,1.188000,0.100000,53.280000,0.394000
25%,8.560000e+02,2.000000,6.571000,4.200000e+01,0.000000,0.000000,183.339500,0.169000,1.100000,6.364250,...,4466.507000,0.500000,167.295000,5.290000,1.900000,21.600000,20.859000,1.300000,67.880000,0.602000
50%,9.351000e+03,66.000000,80.714000,2.910000e+02,2.000000,1.143000,1254.710000,7.149000,9.483000,35.691500,...,12951.839000,2.000000,242.648000,7.110000,6.300000,31.400000,49.839000,2.400000,74.530000,0.748000
75%,1.011765e+05,726.000000,757.500000,2.833000e+03,17.000000,13.000000,8886.468000,63.589000,71.391000,223.000500,...,27216.445000,21.200000,329.635000,10.080000,19.300000,41.100000,83.241000,3.861000,78.730000,0.848000
max,1.365008e+08,880812.000000,739642.714000,2.944771e+06,17904.000000,14433.000000,162829.224000,8652.658000,2648.773000,2606.970000,...,116935.600000,77.600000,724.417000,30.530000,44.000000,78.100000,98.999000,13.800000,86.750000,0.957000